### ISSUE TITLE
Null Pointer exception while running the application

### ISSUE THREAD

**Issue by Sursingh456** [SaiUpadhyayula/langchain4j-pdf-assistant#1]

**Comment by Deathslayer89** [comment]
Hi @SaiUpadhyayula  i too got the same error , tried to debug the application but couldn't find any solution, this is the specific error 
![image](https://github.com/SaiUpadhyayula/langchain4j-pdf-assistant/assets/72866547/84535af8-b4e5-4403-b00b-6eb3050e28fa), here is my code https://github.com/Deathslayer89/pdfassistant

**Comment by SaiUpadhyayula** [comment]
@Sursingh456 @Deathslayer89 Sorry for the late reply, I don't have the AstroDB token with me anymore, so I can't test what went wrong, but you can try the new branch I just created, where we use Ollama instead of OpenAI and PGVector instead of AstroDB. This is working
